title: "Shadrach's Blog"
description: "Computational chemistry, workflows, ideas and personal reflections"
theme: minima
minima:
  header_pages:
    - index.md
    - about.md
    - post.md
    - research.md
    - projects.md
    - tutorials.md
    
